org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=1G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true
# Bypass the Java 25 version check crash
android.suppressUnsupportedCompileSdk=35
android.java.version.check=false
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=true
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
# Increase memory for Kotlin compiler
kotlin.daemon.jvm.options=-Xmx2048M
# Run compiler in-process to avoid daemon connection issues
kotlin.compiler.execution.strategy=in-process
